version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      CONTEXT_TEST: 0
      CONTEXT_TEST_ENV: ${CONTEXT_TEST}-ENV
      EVAL_CONTEXT_TEST_ENV: export HOGE="$(eval "${CONTEXT_TEST_ENV}")"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Display SHA1, name-rev and branch-contains
          command: |
            echo "$CIRCLE_SHA1"
            git name-rev $CIRCLE_SHA1
            git branch --contains $CIRCLE_SHA1
      - run:
          name: Display branch and tag
          command: |
            echo $CIRCLE_BRANCH
            echo $CIRCLE_TAG
      - run:
          name: Context test01
          command: |
            export CONTEXT_TEST=1
            echo $CONTEXT_TEST
            echo $CONTEXT_TEST_ENV
      - run:
          name: Context test02
          command: |
            echo $CONTEXT_TEST
            echo $CONTEXT_TEST_ENV
      - run:
          name: Context test03 (eval)
          command: |
            eval "${EVAL_CONTEXT_TEST_ENV}"
            echo "CONTEXT_TEST: $CONTEXT_TEST"
            echo "CONTEXT_TEST_ENV: $CONTEXT_TEST_ENV"
            echo "EVAL_CONTEXT_TEST: $EVAL_CONTEXT_TEST_ENV"
            echo "HOGE: $HOGE"
      - run:
          name: Build example
          command: |
            echo 'Build finished!'

  deploy_prd:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - deploy:
          name: Deploy Prod example
          command: |
            echo "CIRCLE_BRANCH: ${CIRCLE_BRANCH}"
            echo "CIRCLE_TAG: ${CIRCLE_TAG}"

  deploy_dev:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - deploy:
          name: Deploy Dev example
          command: |
            echo "CIRCLE_BRANCH: ${CIRCLE_BRANCH}"
            echo "CIRCLE_TAG: ${CIRCLE_TAG}"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
            tags:
              only: /.*/
      - deploy_prd:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy_dev:
          requires:
            - build
          filters:
            branches:
              only: master
